language: php
php:
  - 5.6
services:
  - mysql
  - postgresql
install:
  - /home/travis/.phpenv/versions/5.6/bin/composer install
  - phpenv rehash
before_script:
  - mkdir -p build/logs
  - mysql -e 'create database testing_db;'
  - psql -c 'create database testing_db;' -U postgres
script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
