language: php
php:
  - 5.6
services:
  - mysql
  - postgresql
install:
  - pear install pear/PHP_CodeSniffer
  - /home/travis/.phpenv/versions/5.6/bin/composer install
  - composer require satooshi/php-coveralls
  - phpenv rehash 
before_script:
  - mkdir -p build/logs
  - mysql -e 'create database testing_db;'
  - psql -c 'create database testing_db;' -U postgres
script:
  - phpcs
  - phpunit --coverage-clover build/logs/clover.xml
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
