language: php
php:
  - 5.6
services:
  - mysql
  - postgresql
install:
  - pear install pear/PHP_CodeSniffer
  - /home/travis/.phpenv/versions/5.6/bin/composer install
  - phpenv rehash 
before_script:
  - mysql -e 'create database testing_db;'
  - psql -c 'create database testing_db;' -U postgres
script:
  - phpunit
  - phpcs
